#!/bin/bash
# =============================================================================
# ServerSH Auto-CLI - Interactive Configuration Tool
# =============================================================================

set -euo pipefail

# Version
SCRIPT_VERSION="1.0.0"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# =============================================================================
# LOGGING FUNCTIONS
# =============================================================================

show_banner() {
    echo -e "${CYAN}"
    cat << 'EOF'
 ____                       ____  _
|  _ \ __ _ _ __   ___ _ __/ ___|| | ___
| |_) / _` | '_ \ / _ \ '__\___ \| |/ _ \
|  _ < (_| | |_) |  __/ |   ___) | |  __/
|_| \_\__,_| .__/ \___|_|  |____/|_|\___|
           |_|
            S E R V E R   M A N A G E M E N T
EOF
    echo -e "${NC}"
    echo -e "${PURPLE}Auto-CLI v$SCRIPT_VERSION • Interactive Configuration${NC}"
    echo ""
}

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_step() {
    echo -e "${CYAN}[STEP]${NC} $1"
}

read_input() {
    local prompt="$1"
    local default="$2"
    local var_name="$3"
    local validation="${4:-}"
    local value

    while true; do
        if [[ -n "$default" ]]; then
            read -p "${prompt} [${default}]: " value
            value="${value:-$default}"
        else
            read -p "${prompt}: " value
        fi

        # Validation
        case "$validation" in
            "yesno")
                if [[ "$value" =~ ^(yes|no|true|false|1|0)$ ]]; then
                    # Convert to true/false
                    if [[ "$value" =~ ^(yes|true|1)$ ]]; then
                        value="true"
                    else
                        value="false"
                    fi
                    break
                else
                    log_error "Please enter 'yes' or 'no'"
                    continue
                fi
                ;;
            "port")
                if [[ "$value" =~ ^[0-9]+$ ]] && [[ "$value" -ge 1 ]] && [[ "$value" -le 65535 ]]; then
                    break
                else
                    log_error "Please enter a valid port (1-65535)"
                    continue
                fi
                ;;
            "email")
                if [[ "$value" =~ ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; then
                    break
                else
                    log_error "Please enter a valid email address"
                    continue
                fi
                ;;
            *)
                break
                ;;
        esac
    done

    # Export variable
    export "$var_name"="$value"
}

show_preview() {
    log_step "Configuration Preview"
    echo ""

    echo -e "${CYAN}System Configuration:${NC}"
    echo "  Hostname: ${SERVERSH_HOSTNAME:-myserver}"
    echo "  Username: ${SERVERSH_USERNAME:-admin}"
    echo "  SSH Port: ${SERVERSH_SSH_PREFERRED_PORT:-2222}"
    echo "  Docker: ${SERVERSH_DOCKER_ENABLE:-true}"
    echo "  Web UI Port: ${SERVERSH_WEB_UI_PORT:-8080}"
    echo "  Monitoring: ${SERVERSH_PROMETHEUS_ENABLE:-true}"
    echo ""

    echo -e "${CYAN}Security Configuration:${NC}"
    echo "  SSH Enable: ${SERVERSH_SSH_ENABLE:-true}"
    echo "  Firewall: ${SERVERSH_FIREWALL_ENABLE:-true}"
    echo "  Fail2ban: ${SERVERSH_INSTALL_FAIL2BAN:-true}"
    echo ""

    echo -e "${CYAN}Backup Configuration:${NC}"
    echo "  Backup Enable: ${SERVERSH_BACKUP_ENABLE:-false}"
    echo "  Backup Schedule: ${SERVERSH_BACKUP_SCHEDULE:-0 2 * * *}"
    echo ""
}

create_config_file() {
    log_step "Creating configuration file..."

    # Backup existing .env if it exists
    if [[ -f .env ]]; then
        cp .env ".env.backup.$(date +%Y%m%d_%H%M%S)"
        log_info "Existing .env backed up"
    fi

    # Create new .env file with proper escaping
    cat > .env << ENDOFFILE
# =============================================================================
# ServerSH Configuration - Generated by Auto-CLI
# =============================================================================
# Created: $(date)
# Version: $SCRIPT_VERSION

# =============================================================================
# SYSTEM CONFIGURATION
# =============================================================================

# System updates
SERVERSH_UPDATE_AUTO=${SERVERSH_UPDATE_AUTO:-true}
SERVERSH_UPDATE_SECURITY_ONLY=${SERVERSH_UPDATE_SECURITY_ONLY:-false}
SERVERSH_UPDATE_CLEANUP=${SERVERSH_UPDATE_CLEANUP:-true}

# Hostname configuration
SERVERSH_HOSTNAME=${SERVERSH_HOSTNAME:-myserver}
SERVERSH_FQDN=${SERVERSH_FQDN:-myserver.example.com}
SERVERSH_HOSTNAME_UPDATE_HOSTS=true
SERVERSH_HOSTNAME_VALIDATE_DNS=false

# =============================================================================
# USER CONFIGURATION
# =============================================================================

# Main user account
SERVERSH_CREATE_USER=true
SERVERSH_USERNAME=${SERVERSH_USERNAME:-admin}
SERVERSH_USER_PASSWORD=${SERVERSH_USER_PASSWORD:-SecurePassword123!}
SERVERSH_USER_SSH_KEY=true
SERVERSH_USER_SUDO=true
SERVERSH_USER_SHELL=/bin/bash

# =============================================================================
# SSH CONFIGURATION
# =============================================================================

# SSH hardening
SERVERSH_SSH_ENABLE=${SERVERSH_SSH_ENABLE:-true}
SERVERSH_SSH_INTERACTIVE_PORT=${SERVERSH_SSH_INTERACTIVE_PORT:-true}
SERVERSH_SSH_PREFERRED_PORT=${SERVERSH_SSH_PREFERRED_PORT:-2222}
SERVERSH_SSH_SCAN_RANGES="2000-2999,4000-4999,5000-5999,6000-6999,7000-7999,8000-8999,9000-9999"
SERVERSH_SSH_BACKUP_CONFIG=true

# SSH security settings
SERVERSH_SSH_PERMIT_ROOT_LOGIN=no
SERVERSH_SSH_PASSWORD_AUTHENTICATION=no
SERVERSH_SSH_PERMIT_EMPTY_PASSWORDS=no
SERVERSH_SSH_X11_FORWARDING=no
SERVERSH_SSH_CLIENT_ALIVE_INTERVAL=300
SERVERSH_SSH_CLIENT_ALIVE_COUNT_MAX=2
SERVERSH_SSH_MAX_AUTH_TRIES=3
SERVERSH_SSH_MAX_SESSIONS=10

# =============================================================================
# FIREWALL CONFIGURATION
# =============================================================================

# Firewall settings
SERVERSH_FIREWALL_ENABLE=${SERVERSH_FIREWALL_ENABLE:-true}
SERVERSH_FIREWALL_TYPE=auto
SERVERSH_FIREWALL_DEFAULT_POLICY=deny
SERVERSH_FIREWALL_ALLOW_SSH=true
SERVERSH_FIREWALL_LOG_RULES=true

# Allowed ports (comma-separated, format: port/protocol)
SERVERSH_FIREWALL_ALLOWED_PORTS="80/tcp,443/tcp"

# =============================================================================
# DOCKER CONFIGURATION
# =============================================================================

# Docker installation
SERVERSH_DOCKER_ENABLE=${SERVERSH_DOCKER_ENABLE:-true}
SERVERSH_DOCKER_VERSION=latest
SERVERSH_DOCKER_INSTALL_COMPOSE=true
SERVERSH_DOCKER_COMPOSE_VERSION=latest
SERVERSH_DOCKER_USER=${SERVERSH_USERNAME:-admin}

# Docker network configuration
SERVERSH_DOCKER_NETWORK_MTU=1450
SERVERSH_DOCKER_NETWORK_IPV6=true
SERVERSH_DOCKER_NETWORK_NAME=newt_talk
SERVERSH_DOCKER_IPV6_SUBNET=2001:db8:1::/64
SERVERSH_DOCKER_IP_POOL=172.25.0.0/16
SERVERSH_DOCKER_IP_POOL_SIZE=24

# =============================================================================
# PROMETHEUS MONITORING CONFIGURATION
# =============================================================================

# Prometheus installation
SERVERSH_PROMETHEUS_ENABLE=${SERVERSH_PROMETHEUS_ENABLE:-true}
SERVERSH_PROMETHEUS_VERSION=latest
SERVERSH_PROMETHEUS_PORT=9090
SERVERSH_PROMETHEUS_RETENTION=15d
SERVERSH_PROMETHEUS_STORAGE_PATH=/var/lib/prometheus
SERVERSH_PROMETHEUS_ENABLE_SERVICE=true

# Node Exporter
SERVERSH_NODE_EXPORTER_ENABLE=true
SERVERSH_NODE_EXPORTER_VERSION=latest
SERVERSH_NODE_EXPORTER_PORT=9100

# =============================================================================
# WEB UI CONFIGURATION
# =============================================================================

# Web UI settings
SERVERSH_WEB_UI_ENABLE=${SERVERSH_WEB_UI_ENABLE:-true}
SERVERSH_WEB_UI_PORT=${SERVERSH_WEB_UI_PORT:-8080}
SERVERSH_WEB_UI_HOST=0.0.0.0
SERVERSH_WEB_UI_SSL=false
SERVERSH_WEB_UI_USER=serversh
SERVERSH_WEB_UI_SYSTEMD_SERVICE=true

# =============================================================================
# BACKUP CONFIGURATION
# =============================================================================

# Backup basic configuration
SERVERSH_BACKUP_ENABLE=${SERVERSH_BACKUP_ENABLE:-false}
SERVERSH_BACKUP_BASE_DIR=/backup
SERVERSH_BACKUP_SCHEDULE="0 2 * * *"
SERVERSH_BACKUP_RETENTION_DAYS=30
SERVERSH_BACKUP_TYPES="full"
SERVERSH_BACKUP_SOURCES="/etc,/home,/var/www,/opt,/var/lib,/usr/local"

# =============================================================================
# SECURITY CONFIGURATION
# =============================================================================

# Fail2ban installation
SERVERSH_INSTALL_FAIL2BAN=${SERVERSH_INSTALL_FAIL2BAN:-true}
SERVERSH_FAIL2BAN_MAXRETRY=3
SERVERSH_FAIL2BAN_FINDTIME=600
SERVERSH_FAIL2BAN_BANTIME=3600
SERVERSH_FAIL2BAN_DESTEMAIL=${SERVERSH_FAIL2BAN_DESTEMAIL:-admin@example.com}
SERVERSH_FAIL2BAN_SENDMAIL=true
SERVERSH_FAIL2BAN_ACTION="%(action_mw)s"

# =============================================================================
# TAILSCALE CONFIGURATION
# =============================================================================

# Tailscale VPN
SERVERSH_INSTALL_TAILSCALE=${SERVERSH_INSTALL_TAILSCALE:-true}
SERVERSH_TAILSCALE_LOGIN_METHOD=interactive
SERVERSH_TAILSCALE_AUTH_KEY="${SERVERSH_TAILSCALE_SSH_KEY:-}"
SERVERSH_TAILSCALE_ARGS="--accept-dns=false --accept-routes=true"
SERVERSH_TAILSCALE_SSH=${SERVERSH_TAILSCALE_SSH:-true}
SERVERSH_TAILSCALE_MAGICDNS=${SERVERSH_TAILSCALE_MAGICDNS:-true}

# =============================================================================
# INSTALLATION CONFIGURATION
# =============================================================================

# General installation settings
SERVERSH_AUTO_BACKUP=true
SERVERSH_VERIFICATION=true
SERVERSH_ROLLBACK_ON_ERROR=true
SERVERSH_LOG_LEVEL=INFO
SERVERSH_PARALLEL_INSTALL=false
SERVERSH_DRY_RUN=false

# Installation module order
SERVERSH_MODULE_ORDER="system/update,system/hostname,security/users,security/ssh,security/firewall,container/docker,monitoring/prometheus,backup/backup_recovery,applications/optional_software"

# =============================================================================
# ADDITIONAL SOFTWARE CONFIGURATION
# =============================================================================

# Additional system packages
SERVERSH_ADDITIONAL_PACKAGES="htop,vim,git,curl,wget,unzip,tree,ncdu,rsync"

# Development tools
SERVERSH_INSTALL_DEV_TOOLS=${SERVERSH_INSTALL_DEV_TOOLS:-false}
SERVERSH_DEV_PACKAGES="build-essential,python3,python3-pip,nodejs,npm"

# Docker extras
SERVERSH_INSTALL_DOCKER_EXTRAS=${SERVERSH_INSTALL_DOCKER_EXTRAS:-false}
SERVERSH_DOCKER_EXTRAS="docker-compose,ctop"

# Monitoring tools
SERVERSH_INSTALL_MONITORING_TOOLS=${SERVERSH_INSTALL_MONITORING_TOOLS:-false}
SERVERSH_MONITORING_PACKAGES="iotop,nethogs,sysstat,lm-sensors,atop"

# =============================================================================
# DEPLOYMENT CONFIGURATION
# =============================================================================

# Deployment settings
SERVERSH_DEPLOY_MODE=interactive
SERVERSH_DEPLOY_PROFILE=custom
SERVERSH_VERSION=$SCRIPT_VERSION
SERVERSH_INSTALLATION_DATE=$(date -Iseconds)

# Debug settings
SERVERSH_DEBUG=false
SERVERSH_VERBOSE_OUTPUT=false
SERVERSH_TIMING=false
ENDOFFILE

    log_success "Configuration file created: .env"
}

quick_setup() {
    show_banner

    log_step "ServerSH Interactive Configuration"
    echo "This wizard will guide you through the configuration of your ServerSH installation."
    echo ""

    # System Configuration
    log_step "System Configuration"
    read_input "Server hostname" "myserver" "SERVERSH_HOSTNAME"
    read_input "Main username" "admin" "SERVERSH_USERNAME"
    read_input "User password" "SecurePassword123!" "SERVERSH_USER_PASSWORD"

    echo ""
    read_input "Enable automatic system updates" "true" "SERVERSH_UPDATE_AUTO" "yesno"
    read_input "Security updates only" "false" "SERVERSH_UPDATE_SECURITY_ONLY" "yesno"
    read_input "Package cleanup after updates" "true" "SERVERSH_UPDATE_CLEANUP" "yesno"

    # SSH Configuration
    echo ""
    log_step "SSH Configuration"
    read_input "Enable SSH" "true" "SERVERSH_SSH_ENABLE" "yesno"
    read_input "Interactive SSH port selection" "true" "SERVERSH_SSH_INTERACTIVE_PORT" "yesno"
    read_input "Preferred SSH port" "2222" "SERVERSH_SSH_PREFERRED_PORT" "port"

    # Security Configuration
    echo ""
    log_step "Security Configuration"
    read_input "Enable firewall" "true" "SERVERSH_FIREWALL_ENABLE" "yesno"
    read_input "Install Fail2ban" "true" "SERVERSH_INSTALL_FAIL2BAN" "yesno"
    read_input "Fail2ban destination email" "admin@example.com" "SERVERSH_FAIL2BAN_DESTEMAIL" "email"

    # Docker Configuration
    echo ""
    log_step "Docker Configuration"
    read_input "Enable Docker" "true" "SERVERSH_DOCKER_ENABLE" "yesno"
    read_input "Install Docker Compose" "true" "SERVERSH_DOCKER_INSTALL_COMPOSE" "yesno"

    # Monitoring Configuration
    echo ""
    log_step "Monitoring Configuration"
    read_input "Enable Prometheus monitoring" "true" "SERVERSH_PROMETHEUS_ENABLE" "yesno"
    read_input "Enable Node Exporter" "true" "SERVERSH_NODE_EXPORTER_ENABLE" "yesno"

    # Web UI Configuration
    echo ""
    log_step "Web UI Configuration"
    read_input "Enable Web UI" "true" "SERVERSH_WEB_UI_ENABLE" "yesno"
    read_input "Web UI port" "8080" "SERVERSH_WEB_UI_PORT" "port"

    # Backup Configuration
    echo ""
    log_step "Backup Configuration"
    read_input "Enable backup system" "false" "SERVERSH_BACKUP_ENABLE" "yesno"
    if [[ "${SERVERSH_BACKUP_ENABLE}" == "true" ]]; then
        read_input "Backup schedule (cron format)" "0 2 * * *" "SERVERSH_BACKUP_SCHEDULE"
        read_input "Backup retention days" "30" "SERVERSH_BACKUP_RETENTION_DAYS"
    fi

    # Tailscale Configuration
    echo ""
    log_step "Tailscale VPN Configuration"
    read_input "Install Tailscale" "true" "SERVERSH_INSTALL_TAILSCALE" "yesno"
    if [[ "${SERVERSH_INSTALL_TAILSCALE}" == "true" ]]; then
        read_input "Tailscale SSH" "true" "SERVERSH_TAILSCALE_SSH" "yesno"
        read_input "Tailscale MagicDNS" "true" "SERVERSH_TAILSCALE_MAGICDNS" "yesno"
        read_input "Tailscale auth key (optional)" "" "SERVERSH_TAILSCALE_SSH_KEY"
    fi

    # Optional Software
    echo ""
    log_step "Optional Software Configuration"
    read_input "Install development tools" "false" "SERVERSH_INSTALL_DEV_TOOLS" "yesno"
    read_input "Install monitoring tools" "false" "SERVERSH_INSTALL_MONITORING_TOOLS" "yesno"
    read_input "Install Docker extras" "false" "SERVERSH_INSTALL_DOCKER_EXTRAS" "yesno"

    # Show preview
    echo ""
    show_preview

    # Confirm creation
    echo ""
    read_input "Create configuration file" "yes" "CONFIRM" "yesno"

    if [[ "$CONFIRM" == "true" ]]; then
        create_config_file
        echo ""
        log_success "Configuration completed successfully!"
        echo ""
        log_info "Next steps:"
        echo "  1. Review the generated .env file"
        echo "  2. Run: ./cli.sh install --auto"
        echo "  3. Access Web UI at: http://your-server-ip:${SERVERSH_WEB_UI_PORT:-8080}"
        echo ""
    else
        log_warning "Configuration cancelled"
    fi
}

# =============================================================================
# MAIN FUNCTION
# =============================================================================

main() {
    local command="${1:-interactive}"

    case "$command" in
        "interactive"|"")
            quick_setup
            ;;
        "preview")
            show_preview
            ;;
        "help"|"-h"|"--help")
            cat << EOF
ServerSH Auto-CLI - Interactive Configuration Tool

USAGE:
    $0 [COMMAND]

COMMANDS:
    interactive           Start interactive configuration (default)
    preview              Show current configuration preview
    help                 Show this help message

EXAMPLES:
    $0                    # Start interactive setup
    $0 interactive        # Same as above
    $0 preview           # Show current config
    $0 help              # Show help

The interactive configuration will guide you through setting up your ServerSH
installation with all the options you need.
EOF
            ;;
        *)
            log_error "Unknown command: $command"
            echo "Available commands: interactive, preview, help"
            exit 1
            ;;
    esac
}

# Execute main function
main "$@"